import {
    // Hogar
    Home,
    UtensilsCrossed,
    Bed,
    Bath,
    Armchair,
    DoorOpen,
    Square,
    Lightbulb,
    Monitor,
    Wifi,
    // Viajes y Vacaciones
    Plane,
    Car,
    Train,
    Ship,
    MapPin,
    Compass,
    Camera,
    Luggage,
    Sun,
    Umbrella,
    // Transporte
    Bike,
    Bus,
    Navigation,
    Route,
    // Comodidades
    Wind,
    Droplet,
    Flame,
    Snowflake,
    Shield,
    Key,
    Lock,
    // Actividades
    Waves,
    Mountain,
    TreePine,
    Gamepad,
    Music,
    BookOpen,
    // Servicios
    ShoppingBag,
    Coffee,
    Utensils,
    Candy,
    // Otros
    Star,
    Heart,
    Sparkles,
    Zap,
    // Normas Especificas
    CigaretteOff,
    VolumeX,
    Moon,
    Clock,
    ClipboardList,
    CheckCircle2,
    AlertTriangle,
    Info,
    Smartphone,
    Mail,
    HelpCircle,
    LucideIcon
} from "lucide-react"

// Mapeo completo de códigos Font Awesome a componentes Lucide
// Incluye iconos generales y específicos de normas/guía
export const FA_TO_LUCIDE: Record<string, LucideIcon> = {
    // Generales
    "fas fa-home": Home,
    "fas fa-utensils": UtensilsCrossed,
    "fas fa-bed": Bed,
    "fas fa-bath": Bath,
    "fas fa-couch": Armchair,
    "fas fa-door-open": DoorOpen,
    "fas fa-window-maximize": Square,
    "fas fa-lightbulb": Lightbulb,
    "fas fa-tv": Monitor,
    "fas fa-wifi": Wifi,
    "fas fa-plane": Plane,
    "fas fa-car": Car,
    "fas fa-train": Train,
    "fas fa-ship": Ship,
    "fas fa-map-marker-alt": MapPin,
    "fas fa-compass": Compass,
    "fas fa-camera": Camera,
    "fas fa-suitcase": Luggage,
    "fas fa-sun": Sun,
    "fas fa-umbrella": Umbrella,
    "fas fa-bicycle": Bike,
    "fas fa-bus": Bus,
    "fas fa-map": Navigation,
    "fas fa-route": Route,
    "fas fa-wind": Wind,
    "fas fa-tint": Droplet,
    "fas fa-fire": Flame,
    "fas fa-snowflake": Snowflake,
    "fas fa-shield-alt": Shield,
    "fas fa-key": Key,
    "fas fa-lock": Lock,
    "fas fa-water": Waves,
    "fas fa-mountain": Mountain,
    "fas fa-tree": TreePine,
    "fas fa-gamepad": Gamepad,
    "fas fa-music": Music,
    "fas fa-book": BookOpen,
    "fas fa-shopping-bag": ShoppingBag,
    "fas fa-coffee": Coffee,
    "fas fa-candy-cane": Candy,
    "fas fa-star": Star,
    "fas fa-heart": Heart,
    "fas fa-sparkles": Sparkles,
    "fas fa-bolt": Zap,

    // Normas de la Casa (agregados específicamente)
    "fas fa-smoking-ban": CigaretteOff,
    "fas fa-volume-mute": VolumeX,
    "fas fa-moon": Moon,
    "fas fa-clock": Clock,
    "fas fa-clipboard-list": ClipboardList,
    "fas fa-mobile-alt": Smartphone,
    "fas fa-envelope": Mail,
    "fas fa-info-circle": Info,
    "fas fa-exclamation-triangle": AlertTriangle,
    "fas fa-question-circle": HelpCircle,
}

// Función helper para obtener icono con fallback
export function getIconFromCode(iconCode: string | undefined, defaultIcon: LucideIcon = CheckCircle2): LucideIcon {
    if (!iconCode) return defaultIcon
    return FA_TO_LUCIDE[iconCode] || defaultIcon
}
